version: '3'

services:
  # MySQL
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: default
      MYSQL_USER: user 
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # ### Should use default volume path.
    #volumes:
    #- ./var/lib/mysql:/var/lib/mysql
    #- ./etc/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
    - 3306:3306
